--1.insert 문
--INSERT INTO table_name (column_value, ...) VALUES(column_value, ...)
--주의: 컬럼명 정확히 지켜라, 컬럼명 갯수와 VALUES 갯수가 맞아야한다.
--컬럼명 타입과 VALUES 타입이 같아야한다.
-- NOT NULL, PRIMARY KEY, 등 제약조건을 잘 지켜야한다.

-- DEPT 테이블을 생성한다
CREATE TABLE DEPT(
    DEPTNO NUMBER(2)PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13) NOT NULL
);
--칼럼 DEPTNO에 10번 부서, DNAME에는 ‘ACCOUNTING’을, LOC에는 ‘NEW YORK’을 추가하자
INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (10, 'ACCOUNTING1', 'NEW YORK1'); --이 쿼리문은 ERROR PRIMARY KEY조건이 달려있으면 중복된 값을 넣을 수 없다.
INSERT INTO DEPT VALUES (11, 'ACCOUNTING1', 'NEW YORK1');
INSERT INTO DEPT VALUES (12, 'ACCOUNTING2'); --이 쿼리문은 ERROR INSERT문에서 COLUMN이름을 생략할려면 VALUES 뒤에 모든 COLUMN의 값들이 작성되어야한다.
INSERT INTO DEPT (DEPTNO, DNAME) VALUES (12, 'ACCOUNTING2'); -- NOT NULL 제약조건이 있을경우 작성하지 않으면 ERROR를 반환한다.
INSERT INTO DEPT (DNAME, LOC) VALUES ('ACCOUNTING2', 'NEW YORK2'); --기본적으로 PRIMARY KEY는 NOT NULL이 작성되어있지 않아도 NOT NULL조건을 가진다.
INSERT INTO DEPT VALUES (12, NULL, 'NEW YORK2');
INSERT INTO DEPT VALUES (13, '', 'NEW YORK3');

-- 컬럼 DEPTNO 사이즈 4로 변경 DNAME을 NOT NULL로 변경하시오.
ALTER TABLE DEPT 
MODIFY(DEPTNO NUMBER(4), DNAME VARCHAR2(30) NOT NULL); --ERROR 이미 NULL값이 들어가 있는 컬럼이 있기 때문에 NOT NULL에 실패함

--DNAME이 NULL인 값을 '임시값'으로 변경한다.
UPDATE DEPT SET DNAME = '임시값' 
WHERE DNAME IS NULL;            --UPDATE 문으로 NULL 값에 DEFAULT값을 넣거나 테이블을 초기화 한뒤 위의 쿼리문을 진행

CREATE TABLE TB_CUSTOMER(
    CUSTOMER_CD NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(12) NOT NULL,
    MW_FLG CHAR(1) NOT NULL,
    BIRTH_DAY DATE NOT NULL,
    PHONE_NUMBER CHAR(13),
    EMAIL VARCHAR(20),
    TOTAL_POINT NUMBER DEFAULT 0 NOT NULL,
    REG_DTTM DATE NOT NULL
);

INSERT INTO TB_CUSTOMER VALUES(2017042, '강원진', 'M', DATE'1981-06-03','010-8202-8790','wjgang@navi.com',280300,TIMESTAMP'2017-01-23 13:24:32');
INSERT INTO TB_CUSTOMER VALUES(2017053, '나경숙', 'W', DATE'1989-12-25','010-4509-0043','ksna#@boram.co.kr',4500,TIMESTAMP'2017-02-10 18:09:30');
INSERT INTO TB_CUSTOMER VALUES(2017108, '박승대', 'M', DATE'1971-12-30','','sdpark@haso.com',23450,TIMESTAMP'2017-05-08 20:34:50');


SELECT * FROM DEPT;
SELECT * FROM TB_CUSTOMER;
SELECT CUSTOMER_CD, CUSTOMER_NAME, MW_FLG, BIRTH_DAY, PHONE_NUMBER, EMAIL, TOTAL_POINT, TO_CHAR(REG_DTTM, 'YYYY-MM-DD HH24:MI:SS') AS REG_DTTM FROM TB_CUSTOMER;
SELECT * FROM TAB
WHERE TNAME = 'DEPT';
DESC DEPT;

DROP TABLE TB_CUSTOMER;
DROP TABLE DEPT;